export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{
          background: "aliceblue"
        }}>Header</header>
        {children}
        <footer
        style={{
          background: "lightblue"
        }}>Footer</footer>
        </body>
    </html>
  )
}
